### ISSUE TITLE
should be South Polar?

### ISSUE THREAD

**Issue by thareUSGS** [PlanetMap/csvForWKT#1]
https://github.com/PlanetMap/csvForWKT/blob/f844e608f48efa96b683b2e6b9d8fc69dd66b20a/src/csv2WKT.py#L174

**Comment by J-Christophe** [comment]
You are right.

I fix it in a couple of minutes.

Thanks

Le mer. 29 janv. 2020 à 22:48, Trent Hare <notifications@github.com> a
écrit :
