### ISSUE TITLE
 EPSG:9810 should be "Polar Stereographic (variant A)"

### ISSUE THREAD

**Issue by thareUSGS** [PlanetMap/csvForWKT#5]
https://github.com/PlanetMap/csvForWKT/blob/7077f10374ccbf0d91e66e78446104d84cc0aa1c/src/iprojectedwkt.py#L109

from Even, 
> Regarding 49930, the official EPSG name for the METHOD EPSG:9810 should be "Polar Stereographic (variant A)"

It was nice to have just Stereographic but better to be explicit that it is polar.

**Comment by J-Christophe** [comment]
Only for 30 ? 

When I read the email from Even I replaced each Stereographic by "Polar Stereographic (variant A)" : https://github.com/PlanetMap/csvForWKT/blob/b14782cdbe6cbf1b173d7421ea25cfc366bdddda/src/iprojectedwkt.py#L109-L118

Should I create WKTs with a polar stereographic **projection** for only DATUM.SPHERE ?

**Comment by thareUSGS** [comment]
for all 30 - 40 (ellipse can used, no need for triaxial for proj).
